// Generated by CoffeeScript 1.7.1
(function() {
  var compile, ratio;

  compile = [];

  ratio = [];

  $("#build").on("click", function(e) {
    var Mc, Mr, hh, i, m0, m1, r0, r1, r2, unit, ww, _i, _ref, _results;
    Mc = M($("#c").val()).bool();
    Mr = M($("#r").val()).bool();
    if (!(Mc || Mr)) {
      return;
    }
    if ($("#map").children().length > 1) {
      return;
    }
    $("#placeholder").remove();
    ww = parseInt($("#map").width());
    hh = parseInt($("#map").height());
    r0 = parseInt($("#c").val());
    r1 = parseInt($("#r").val());
    r2 = r0 * r1;
    ratio = [r0, r1];
    m0 = max(ww, hh);
    m1 = max(r0, r1);
    unit = floor(m0 / m1);
    _results = [];
    for (i = _i = 0, _ref = r2 - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      _results.push($("#map").append($("<div/>").addClass("tile").attr("x", i % r2).attr("y", round(i / r2)).attr("s", -1).css({
        "width": unit,
        "height": unit
      })));
    }
    return _results;
  });

  $(document).on("click", ".tile", function(e) {
    var newState, state, ts;
    ts = tileStates;
    state = parseInt($(this).attr("s"));
    newState = (state + 1) % ts.length;
    return $(this).attr("s", newState).css("background-color", ts[newState]);
  });

  $("#cmpl").on("click", function(e) {
    if ($("#map").children().length <= 1) {
      return;
    }
    $("#map").children().each(function(i, el) {
      return compile.push(parseInt($(el).attr("s")));
    });
    compile.unshift(ratio[1]);
    compile.unshift(ratio[0]);
    return console.log(compile.join(","));
  });

}).call(this);
