// Generated by CoffeeScript 1.7.1
(function() {
  window.random = Math.random;

  window.round = Math.round;

  window.floor = Math.floor;

  window.sqrt = Math.sqrt;

  window.log = Math.log;

  window.sin = Math.sin;

  window.cos = Math.cos;

  window.abs = Math.abs;

  window.max = Math.max;

  window.min = Math.min;

  window.pow = Math.pow;

  window.pi = Math.PI;

  window.sqre = function(x) {
    return Math.pow(x, 2);
  };

}).call(this);
